--UPDATE PATH, SCHEMA_USER & SCHEMA_PASSWORD DETAILS

CREATE OR REPLACE directory SCRIPT_FILES
AS
  '--PATH';

CREATE ROLE AUTOMATION_ROLE;
GRANT READ, WRITE ON DIRECTORY SCRIPT_FILES TO --SCHEMA_USER;
GRANT READ, WRITE ON DIRECTORY SCRIPT_FILES TO AUTOMATION_ROLE;
GRANT connect, AUTOMATION_ROLE TO --SCHEMA_USER identified by --SCHEMA_PASSWORD;
GRANT EXECUTE ON SYS.UTL_FILE TO --SCHEMA_USER
