--IF YOU AREN'T EXECUTING SCRIPT IN THE PROCEDURE / OR WANT TO RE EXECUTE THE SCRIPTS STORED IN REPOSITORY TABLE THEN USE THE --CODE BELOW FOR EXECUTING SCRIPT STORED IN THE REPOSITORY TABLE

DECLARE
l_sql CLOB;
BEGIN
  SELECT SCRIPT_CONTENT INTO l_sql FROM SCRIPT_REPOSITORY;
  DBMS_OUTPUT.PUT_LINE(l_sql);
  EXECUTE IMMEDIATE l_sql;
END;
/